### ISSUE TITLE
Issues with Lab 1 step 1

### ISSUE THREAD

**Issue by satan02** [newrelic/nr1-workshop#57]
Lab1 feedback

Why do we do this:
nr1 nerdpack:uuid -gf
npm install
npm start

In the Getting started when we are going to do that again after clicking on the “Let’s explore…” hyperlink”?  Also are we supposed to do a control-c to stop npm?

Step 0 Why do we not run “npm start” after the install?

Step 1 bullet 5, does it matter if we put this before or after the render?  I assume no as JS is async.  Also there is reference to account id 1606862, but that is not in the code snippet above.  Or is it to be in the Render() function?

Step 1 bullet 6, After saving what should I see in the browser?  I get a spinner that doesn’t stop.  I put in an RPM id where my new relic account has the role Nerdpack manager, are there other roles that I need to add? I change to 1606862 and the page loads.  

Step 1 bullet 10, When I inspect the page and go to verbose I do not see what is in the instructions.

**Comment by jaesius** [comment]
The getting started is a simple set up instructions that we've added to each lab to make sure you are ready to start the lab content. The instructions file is tailored to each lab's content. 

Step 0: You don't start the server 'npm start' because you're about to create a Nerdlet the next step.

Step 1 Part 5: Yes, the constructor method needs to be before the render() in the class. More info on the React constructor can be found here: https://reactjs.org/docs/react-component.html#constructor. 

The id 1606862 was replaced with <REPLACE_WITH_YOUR_ACCOUNT_ID>

Step 1 Part 6:  You should see the Hello World from the screenshot.
